name = "CHAOSS"
license = "Apache-2.0"
licenselink = "https://github.com/chaoss/website/blob/main/LICENSE"
description = "Hugo theme for the CHAOSS community website"

[author]
  name = "CHAOSS Community"
  homepage = "https://chaoss.community"
